### PR TITLE
fixes raml2html/raml2html#323

### PR DESCRIPTION
**Pull request by ashlanderr**

### CODE REVIEW

**Comment by kevinrenskers** [comment]
Thanks for the pull request! However, could I ask you to please add a unit test for this?

**Comment by ashlanderr** [comment]
Ok.

**Comment by nickwb** [comment]
I did a five second fix when I verified your bug, it was similar - if a bit more cautious.

```js
    if(obj.type === 'array' && Array.isArray(obj.items) && obj.items.length === 1) {
      obj.items = obj.items[0];
    }
```

It certainly works - though personally I was hoping to understand the cause better before making the change.

Also, it's easy enough to test by adding test cases to `array-of-strings` and `array-of-foo`.

**Comment by ashlanderr** [comment]
Could it be that items have more than one element in array?

**Comment by kevinrenskers** [comment]
@nickwb do you have time to look at this one of these days, and then release a new version of raml2obj? Thanks!

**Comment by nickwb** [comment]
This PR looks good now. I will double check that the tests and linter are passing when I get home, then we'll land this guy on to develop.

Thanks for the contribution, @ashlanderr

**Comment by nickwb** [comment]
Looks good. 👍

**Pull request merged**
