### PR TITLE
Fix types' parent overriding behaviour

### PR DESCRIPTION
**Pull request by psychoo118**
Possible fix for raml2html/raml2html#298

### CODE REVIEW

**Comment by kevinrenskers** [comment]
Can you please add unit tests that test the new behavior, and also make sure that old tests are still working? You can run tests with `npm run test`, if you need more help/info, please ping me or @nickwb here in the comments.

**Comment by psychoo118** [comment]
Running the tests against develop branch before and after adding test cases both resulted in:
```
  28 passing (3s)
  3 failing

  1) raml2obj helloworld.raml should test the /helloworld methods:
     AssertionError: { value: '{\n  "message": "Hello world"\n}' } === '{\n  "message": "Hello world"\n}'
      at Context.it (test/helloworld.spec.js:72:14)

  2) raml2obj parameters.raml should test the /account/find resource:
     AssertionError: { value: 'Naruto Uzumaki' } === 'Naruto Uzumaki'
      at Context.it (test/parameters.spec.js:66:14)

  3) raml2obj parameters.raml should test the /account/{id} resource:
     AssertionError: { value: 'Authorization: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==\n' } === 'Authorization: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==\n'
      at Context.it (test/parameters.spec.js:111:14)
```

**Comment by kevinrenskers** [comment]
Thanks, I noticed the same just now. I fixed them on the develop branch now.

**Comment by psychoo118** [comment]
now 32 passing :)

**Pull request merged**
