### PR TITLE
Make securedBy: [ null ] consistent with no security.

### PR DESCRIPTION
**Pull request by nickwb**
The default **raml2html** template generally leans on the condition of: `{% if method.securedBy.length %}` to determine if there are any security schemes which are applied to a given method.

Unfortunately this isn't an entirely accurate condition, because the RAML 1.0 spec allows the user to specify `securedBy: [ null ]` on a method. One example where this occurs commonly is if you have `securedBy` specified on your root RAML document to some security scheme, but then selectively disable that security scheme on some methods.

In this PR I address this issue by updating `consistency-helpers`, dropping the `securedBy` property from an object if its only element is `null`.

**Note: it looks like develop is behind master at the moment**

### CODE REVIEW

**Comment by kevinrenskers** [comment]
Great work, love that you added tests. Thanks!

**Comment by kevinrenskers** [comment]
By the way, if you'd like to become a member of the raml2html org on github, with push access to all 3 repo's, please let me know.

**Comment by nickwb** [comment]
Thanks Kevin. I'd be quite happy to be a member of the org, though in the short term I will probably stick to using pull requests to avoid any surprises.

**Comment by kevinrenskers** [comment]
Yep, makes sense.

**Pull request merged**
