### PR TITLE
Update raml parser

### PR DESCRIPTION
**Pull request by cebor**
Pulls in the most recent fixes from https://github.com/raml-org/raml-js-parser-2/releases.

What do you think about also change the version to `^1.1.13` with caret?

### CODE REVIEW

**Comment by kevinrenskers** [comment]
They've had some releases with bugs that broke our tests, so at the moment sticking to precise dependency numbers is much safer. I'll test this change in the weekend, thanks.

**Comment by kevinrenskers** [comment]
Sorry for the delay, but I finally got around to testing this. Sadly this causes 5 of our unit tests to fail, so someone needs to dive into this to see if the tests need updating or if raml-js-parser-2 1.1.13 is broken.

@nickwb do you maybe have time to look into this issue?

**Comment by nickwb** [comment]
I'll see if I can take a look in the next day or so.

**Comment by nickwb** [comment]
Tests are failing because the updated parser no longer emits the `required` property on some type definitions. Working that out was easy enough - now to decide if this is a bug in the parser, or whether this is expected behavior.

**Comment by nickwb** [comment]
This does seem to be an intentional change:

```ts
if(universeHelpers.isTypeDeclarationDescendant(definition)){
    var prop = basicNode.highLevel().property();
    if(prop&&!(universeHelpers.isHeadersProperty(prop)
        ||universeHelpers.isQueryParametersProperty(prop)
        ||universeHelpers.isUriParametersProperty(prop)
        ||universeHelpers.isPropertiesProperty(prop)
        ||universeHelpers.isBaseUriParametersProperty(prop))){

        delete obj["required"];
        var metaObj = obj["__METADATA__"]
        if(metaObj){
            var pMetaObj = metaObj["primitiveValuesMeta"];
            if(pMetaObj){
                delete pMetaObj["required"];
            }
        }

    }
}
```

Some reading suggests that the `required` facet is only supposed to be valid on those node types listed above, and this change brings the parser closer to the spec. This would suggest the asserts in **raml2obj** are not valid, and ought to be dropped from the tests.

We'll want to check if anything breaks in **raml2html** templates, but assuming we pass that hurdle I suggest we can proceed with dropping the asserts, updating the parser version, and adding a changelog indicating that the use of the `required` facet is not supported in all of the places it used to be.

**Comment by kevinrenskers** [comment]
Thanks for the research! I agree with your conclusion so I'll merge this PR to develop but won't release anything yet. Could you fix the tests and check raml2html?

**Comment by nickwb** [comment]
Yep. Can do. Looks like we also have a few tests failing on `develop` due to https://github.com/raml2html/raml2obj/pull/22 

(Sorry, I was testing in master before)

**Comment by kevinrenskers** [comment]
Yeah sorry, forgot to mention the tests for that PR. Too bad they were not fixed as part of that PR. I'll actually set up a CI server soon so we get automatic test reports in all PR's.

**Comment by nickwb** [comment]
OK. I've pushed up the fixed tests for `required` on to develop for now. Might take a second pass at the other tests later.

**Comment by nickwb** [comment]
Templates look like they will be fine.

**Comment by nickwb** [comment]
All tests and linter are happy now. 😃

**Comment by kevinrenskers** [comment]
Awesome! We need to coordinate this release together with https://github.com/raml2html/raml2html/pull/303 though, or the rendering of examples will break in raml2html. I haven't looked at that raml2html PR yet, we need to check the visual changes, see if it's all right, then merge and release both projects.

**Comment by kevinrenskers** [comment]
raml2obj is tagged for a 4.0.5 release, just one `npm publish` command away :)

**Comment by nickwb** [comment]
Sorry to stomp on your glory, but I found a bug when testing with the new template. Have pushed a fix to `raml2obj:develop`.

**Comment by kevinrenskers** [comment]
Haha I just move one tag and done

**Comment by kevinrenskers** [comment]
I changed the upcoming release to be 4.1.0 instead of 4.0.5, so that the current version of raml2html won't break (since it's depending on raml2obj 4.0.x).

**Pull request merged**
