### PR TITLE
Release raml2obj 5.0.0

### PR DESCRIPTION
**Pull request by nickwb**
Figured I would open this so we could track any outstanding items prior to releasing 5.0.0.

Are there any other changes we want to capture before releasing?

### CODE REVIEW

**Comment by nickwb** [comment]
Might be worth including a fix for: https://github.com/raml2html/raml2html/issues/326 ?

**Comment by kevinrenskers** [comment]
That memory problem, is that something we can even fix? Wasn't it a problem in the parser?

Otherwise just merge this to develop, seems fine to me.

**Comment by nickwb** [comment]
If you follow Konstantin's comment on that issue, the issue occurs during `_enhanceRamlObj`, which means the cause is either datatype-expansion or it is raml2obj itself. However, that bug has regressed since raml2html 4.0.6, so it seems likely that the issue is one of the changes that we have made recently to raml2obj.

Personally, I'd like to dig in to the issue, but I'm finding myself rather short on time these last couple of weeks.

**Comment by sichvoge** [comment]
We could probably look into datatype-expansion max next week if that helps.

**Comment by kevinrenskers** [comment]
The memory problem is definitely within `datatype-expansion`, so let's get this merged and 5.0.0 released.

**Pull request merged**
