### PR TITLE
Add feature to load API synchronously

### PR DESCRIPTION
**Pull request by m31271n**
Add feature to load API synchronously.

BTW, just testing a simple parse condition is ok for this sync API without writing duplicated tests?

### CODE REVIEW

**Comment by kevinrenskers** [comment]
Thank for the PR. The test doesn't really seem to do much, as you're using the async parse method there. Can you improve the test? :)

I am also wondering about your use case for this synchronous version. Why is this needed?

**Comment by m31271n** [comment]
The test is improved.

It is helpful in a strange historical CLI project. Before handling the real business work, I have to prepare the RAML meta in advance. But, the function for preparation work is a sync function, and I wanna get sync semantic meaning.

If the function for perparation work is async function, then I can: 
```
async function () {
  ...
  const raml = await raml2obj.parse('xxxx')
  ...
}
```
But It is not.

It is a sync function, I have to use raw Promise. If I do that, then I lose the merit of sync-like code which make itself more clear.

So, I add a sync API.

**Comment by kevinrenskers** [comment]
Sorry, but I am going to close this PR for now until more people have the same use case. It's adding more code that needs to be maintained, there are basically no maintainers, and it's only for you. Sorry :(

**Comment by m31271n** [comment]
That is ok.

**Pull request closed without merging**
