### PR TITLE
prefer taking examples from higher level items instead of types

### PR DESCRIPTION
**Pull request by pbininda**
This solves #36 at least for my use case where I have examples for responses and examples for types. With this change, the examples defined for responses overwrite the examples defined for types

### CODE REVIEW

**Comment by kevinrenskers** [comment]
Could you maybe add a unit test for this, that would fail without this fix?

**Comment by pbininda** [comment]
Working on a unit test now.

**Comment by kevinrenskers** [comment]
I see you added more commits, is it ready to review?

**Comment by pbininda** [comment]
Yes, I added the requested unit tests

**Pull request merged**
