### PR TITLE
update consistency-helpers.js

### PR DESCRIPTION
**Pull request by MichaelIT**
keep raml object example facet (displayName, description...).

### CODE REVIEW

**Comment by MichaelIT** [comment]
I want to help to solve the problem : 
Example's `description` and `displayName` not rendered
https://github.com/raml2html/raml2html/issues/301

**Comment by kevinrenskers** [comment]
Thank you for the pull request! This is a breaking change, which causes tools that use raml2obj to, well, break. They'll need to adapt this new format. 

While I think it's a good change, I also think we should wait a while with merging it - bundle it with other big changes.

**Comment by MichaelIT** [comment]
yes, I agree with u, hope it will be soon.

**Comment by sichvoge** [comment]
@kevinrenskers what do you think the bigger change should be?

**Comment by kevinrenskers** [comment]
I'm not sure, but it feels like this change by itself is just slightly too light to justify a breaking change release. That said, if we want this is, isn't no big problem for us.

**Pull request merged**
